name: 014 basics MatrixStrategy CI/CD
on:
    workflow_dispatch:

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        strategy:
          max-parallel: 2
          matrix:
            os: [windows-latest, macos-latest, ubuntu-latest]
            node-version: [10, 12, 14]
        steps:
            - name: Print Hello World
              run: echo "Hello World"
