name: 017 Basics Container CI/CD
on:
    workflow_dispatch:
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        container:
          image: php:7.4
        steps:
            - name: print version php
              run: php -v

            - name: install redis
              run: apt-get update && apt-get install -y redis

    job2:
        runs-on: ubuntu-latest
        container:
          image: redis:latest
        steps:
            - name: access redis
              run: redis-cli ping
