name: 01 Basics CI/CD
on:
  pull_request:
    types: [closed]
    branches-ignore:
      - main
#  push:
#    branches:
#      - main
#      - develop

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
