name: 02 Basics Filtering Event CI/CD
on:
  push:
    paths:
      - routes/**.php
#    tags:
#      - v*
#  pull_request:
#    types: [closed]
#    branches:
#      - main

jobs:
  print-hello-world:
#    if: github.event.pull_request.merged == true  # ← الشرط ده مهم جدًا
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
