name: 020 ExampleCommentingOnPr CI/CD
on:
    pull_request:
      types: [closed]

permissions:
  issues: write


jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4.2.2

            - name: comment on pr
              run: gh pr comment $PR_NUMBER --body "Hi from GitHub CLI"
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                PR_NUMBER: ${{ github.event.pull_request.number }}
