name: 021 ExampleLaravelPint CI/CD
on:
  push:
    branches: [ main ]

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: install dependencies
              run: composer install

            - name: install laravel pint
              run: composer require laravel/pint --dev

            - name: run laravel pint
              run: ./vendor/bin/pint

            - name: commit changes
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git commit -am "pint" --allow-empty

            - name: push changes
              run: git push
