name: 022 Basics Laravel test

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: enable mysql
        run: |
          sudo systemctl start mysql.service
          mysql -e "CREATE DATABASE apiwebsite"

      - name: install dependencies
        run: composer install -q

      - name: prepare project
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: run tests
        run: php artisan test --compact
