name: 05 Basics Context CI/CD
run-name: ${{ github.actor }} explaining the context try number ${{ github.run_number }}
on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context Data
        run: echo "${{ github['repository_owner'] }}"
#        run: echo "${{ github.actor }}"
