name: 07 Basics environment Variables CI/CD
on:
    workflow_dispatch:

# workflow scope
env:
  MY_NAME: "Nashaat"
  My_age: 21
  my_address: "mansoura"

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        # job scope
        env:
          skills: "html, css, js"
        steps:
            - name: Print Info
              run: echo "my Name is ${{env.MY_NAME}} and my age is ${{env.My_age}} and the address is ${{env.my_address}}"

            - name: Print skills
              run: echo "my skills are ${{env.skills}}"

    print-hello-world-2:
      runs-on: ubuntu-latest
      steps:
        - name: Print phone
          # step scope
          env:
            phone: 0123456789
          run: echo "my phone number is ${{env.phone}}"
