name: 08 Basics Configuration Variables CI/CD

on:
    workflow_dispatch:

# the configuration variable seen by the all workflows in the repository
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello World"

            - name: Print Project Name
              run: echo "${{ vars.PROJECT_NAME }}"
