name: 09 basics Secrets Variables CI/CD
on:
    workflow_dispatch:

# the secret variable seen by the all workflows in the repository
# different from the configuration variable is that it is not visible in the UI (مش يظهر للمستخدم)
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Print integration Credentials
              run: echo ${{ secrets.INTEGRATION_CREDENTIALS }}
