name: Laravel CI/CD

on:
  push:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: apiwebsite
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: laravel_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u laravel_user -plaravel_pass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: apiwebsite
          DB_USERNAME: laravel_user
          DB_PASSWORD: laravel_pass

      - name: Run tests
        run: php artisan test
